name: ImageLib
description: 2D image effects library
version: 2.8.1
homepage: https://github.com/FarragoFiction/ImageLib
author: paradoxLands

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  CommonLib:
    git: git://github.com/FarragoFiction/CommonLib.git
  LoaderLib:
    git: git://github.com/FarragoFiction/LoaderLib.git

dev_dependencies:
  test: ^1.0.0
  build_runner: ^1.0.0
  build_test: ^0.10.2
  build_web_compilers: ^0.4.0
